### PR TITLE
Add CMake build script

### PR DESCRIPTION
**Pull request by ccawley2011**
This is a modified version of the script that was previously in the SDL_mixer repository.

### CODE REVIEW

**Comment by sezero** [comment]
> This is a modified version of the script that was previously in the SDL_mixer repository.

It carries over many unnecessary things from that previous one, like installing (as if we need
it here), -O3 -> -Os optimizer changing which looks like Vitaly's personal preferences among
others.

Why do we actually really need this one though? And if we truly need and want this,
it would be better to adapt from mainstream libvorbis cmake'ry.

**Comment by ccawley2011** [comment]
I agree that this needs to be rewritten at some point, but unfortunately building SDL_mixer with `-DSUPPORT_OGG=ON` is broken without this.

**Comment by sezero** [comment]
How about changing tremor option to plain libvorbis in SDL_mixer's cmake'ry?

**Comment by sezero** [comment]
> How about changing tremor option to plain libvorbis in SDL_mixer's cmake'ry?

I mean, the following works for me locally. I may have missed a few things though.
What do you say?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 06dd28b..af88a92 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,7 +18,7 @@ set(FULL_VERSION "${MAJOR_VERSION}.${MINOR_VERSION}.${MICRO_VERSION}")
 
 option(SUPPORT_WAV "Support loading WAVE music" ON)
 option(SUPPORT_FLAC "Support loading FLAC music with libFLAC" OFF)
-option(SUPPORT_OGG "Support loading OGG Vorbis music via Tremor" OFF)
+option(SUPPORT_OGG "Support loading OGG Vorbis music via libvorbis" OFF)
 option(SUPPORT_MP3_MPG123 "Support loading MP3 music via MPG123" OFF)
 option(SUPPORT_MOD_MODPLUG "Support loading MOD music via modplug" OFF)
 option(SUPPORT_MID_TIMIDITY "Support loading MIDI music via TiMidity" ON)
@@ -137,10 +137,10 @@ if (SUPPORT_FLAC)
 endif()
 
 if (SUPPORT_OGG)
-    target_compile_definitions(SDL2_mixer PRIVATE -DMUSIC_OGG -DOGG_USE_TREMOR -DOGG_HEADER=<ivorbisfile.h>)
-    add_subdirectory(external/tremor)
-    target_include_directories(SDL2_mixer PRIVATE external/tremor)
-    target_link_libraries(SDL2_mixer PRIVATE vorbisidec ogg)
+    target_compile_definitions(SDL2_mixer PRIVATE -DMUSIC_OGG)
+    add_subdirectory(external/vorbis)
+    target_include_directories(SDL2_mixer PRIVATE external/vorbis/include)
+    target_link_libraries(SDL2_mixer PRIVATE vorbisfile vorbis ogg)
 endif()
 
 if (SUPPORT_MP3_MPG123)
```

**Comment by sezero** [comment]
Besides the above (why the hell was tremor the default in SDL_mixer's cmake'ry...)
a possible cmake script for tremor shoul be as simple as the one added in libjpeg:
https://github.com/libsdl-org/jpeg/blob/9dd8272228382d343120ca0dd17353c45b24ea76/CMakeLists.txt
... possible options may include shared/static building, not much else unless really
necessary.

**Comment by ccawley2011** [comment]
> > How about changing tremor option to plain libvorbis in SDL_mixer's cmake'ry?
> 
> I mean, the following works for me locally. I may have missed a few things though. What do you say?

This looks fine.

> (why the hell was tremor the default in SDL_mixer's cmake'ry...)

I suspect it's because the original version of the CMake script was specific to Android, and copied most of the logic from `Android.mk`, which uses Tremor. Switching to libvorbis for CMake builds shouldn't be too much of a problem for Android, since IIRC modern NDKs don't support targetting ARM CPUs without VFP, which is where using Tremor is usually more beneficial.

**Comment by sezero** [comment]
OK I pushed my patch to SDL_mixer.

Shall I keep this open so you can provide an improved tremor cmake?

**Comment by ccawley2011** [comment]
> OK I pushed my patch to SDL_mixer.
> 
> Shall I keep this open so you can provide an improved tremor cmake?

I'll look into this, but I'll probably start a new PR on a separate branch once I've got something working.

**Pull request closed without merging**
